apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hdfc-ingress
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /internetbanking
            pathType: Prefix
            backend:
              service:
                name: hdfc-service
                port:
                  number: 80

          - path: /insurance
            pathType: Prefix
            backend:
              service:
                name: hdfc-service
                port:
                  number: 80

          - path: /loans
            pathType: Prefix
            backend:
              service:
                name: hdfc-service
                port:
                  number: 80

          - path: /mobilebanking
            pathType: Prefix
            backend:
              service:
                name: hdfc-service
                port:
                  number: 80
