FROM nginx:alpine

COPY insurance /usr/share/nginx/html/insurance
COPY internetbanking /usr/share/nginx/html/internetbanking
COPY loans /usr/share/nginx/html/loans
COPY mobilebanking /usr/share/nginx/html/mobilebanking

EXPOSE 80
