#!/bin/bash
set -e

echo "======================================"
echo "Worker Node Check"
echo "RUN THIS ON WORKER"
echo "======================================"

echo ""
echo "Hostname:"
hostname

echo ""
echo "Private IP:"
hostname -I

echo ""
echo "Kubelet status:"
systemctl --no-pager --full status kubelet | head -20

echo ""
echo "Containerd status:"
systemctl --no-pager --full status containerd | head -20

echo ""
echo "If the Worker has not joined yet:"
echo "Run the exact 'kubeadm join ...' command generated by the Master."

echo ""
echo "The final node check must be done on MASTER:"
echo "kubectl get nodes"
